import type { Metadata } from "next";
import { ABeeZee } from "next/font/google";
import "./globals.css";

const aBeeZee = ABeeZee({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://unpkg.com/@phosphor-icons/web@2.1.1"
          async
        ></script>
      </head>
      <body className={`${aBeeZee.className} antialiased`}>{children}</body>
    </html>
  );
}
